apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb-service
  name: mongodb-service
  namespace: default
spec:
  ports:
    - name: http
      protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: mongodb-deployment
  type: ClusterIP
status:
  loadBalancer: {}
